version: '2'

services:
  memcache:
    container_name: memcache_1
    image: memcached:alpine
  memcache_ssl:
    container_name: memcache_ssl
    image: memcached:alpine
    command: memcached -p 31211 --enable-ssl -o ssl_chain_cert=/etc/localcerts/memcache.cert,ssl_key=/etc/localcerts/memcache.key -vvv
    volumes:
      - "./docker/localcerts:/etc/localcerts"
    ports:
      - "31211:31211"
  memcache_sasl:
    container_name: memcache_sasl
    build:
      context: ./docker/sasl
  toxiproxy:
    build:
      context: ./docker/toxiproxy
    environment:
      PROXIES: "memcache:21211:memcache_1:11211,memcache_sasl:9494:memcache_sasl:11211"
    depends_on:
      - memcache
    ports:
      - "21211:21211"
      - "9494:9494"
      - "8474:8474"


